CREATE TABLE PAIS(
ID NUMBER PRIMARY KEY,
NOME VARCHAR(30),
DESCRICAO VARCHAR(30)
);

CREATE TABLE ESTADO(
ID NUMBER PRIMARY KEY,
ID_PAIS NUMBER NOT NULL,
NOME VARCHAR(30),
DESCRICAO VARCHAR(30)
);

CREATE TABLE CIDADE(
ID NUMBER PRIMARY KEY,
ID_ESTADO NUMBER NOT NULL,
NOME VARCHAR(30),
DESCRICAO VARCHAR(30)
);

CREATE TABLE BAIRRO(
ID NUMBER PRIMARY KEY,
ID_CIDADE NUMBER NOT NULL,
NOME VARCHAR(30),
DESCRICAO VARCHAR(30)
);

CREATE TABLE RUA(
ID NUMBER PRIMARY KEY,
ID_BAIRRO NUMBER NOT NULL,
NOME VARCHAR(30),
NUMERO NUMBER,
DESCRICAO VARCHAR(30)
);

CREATE TABLE ENDERECO(
ID NUMBER PRIMARY KEY,
ID_RUA NUMBER NOT NULL
);

CREATE TABLE INFORMACOES_PESSOAIS(
ID NUMBER PRIMARY KEY,
ID_ENDERECO NUMBER NOT NULL,
NOME_COMPLETO VARCHAR(40),
DATA_NASCIMENTO DATE,
GENERO VARCHAR(20),
TELEFONE CHAR(11),
EMAIL VARCHAR(50)
);

CREATE TABLE CONTATO_EMPRESA(
ID NUMBER PRIMARY KEY,
ID_INFORMACOES_PESSOAIS NUMBER NOT NULL,
CARGO_CONTATO VARCHAR(30)
);

CREATE TABLE DADOS_EMPRESARIAIS(
ID NUMBER PRIMARY KEY,
ID_CONTATO_EMPRESA NUMBER NOT NULL,
ID_PRODUTO NUMBER NOT NULL,
ID_ENDERECO NUMBER NOT NULL,
NOME_EMPRESA VARCHAR(30),
SETOR VARCHAR(30),
NUMERO_REGISTRO CHAR(30)
);

CREATE TABLE PRODUTO(
ID NUMBER PRIMARY KEY,
TIPO VARCHAR(30),
DESCRICAO VARCHAR(30),
PRECO CHAR(30)
);

ALTER TABLE ESTADO ADD CONSTRAINT FK_PAIS 
    FOREIGN KEY (ID_PAIS) 
    REFERENCES PAIS(ID);

ALTER TABLE CIDADE ADD CONSTRAINT FK_ESTADO
    FOREIGN KEY (ID_ESTADO)
    REFERENCES ESTADO(ID);
    
ALTER TABLE BAIRRO ADD CONSTRAINT FK_CIDADE
    FOREIGN KEY (ID_CIDADE)
    REFERENCES CIDADE(ID);
    
ALTER TABLE RUA ADD CONSTRAINT FK_BAIRRO
    FOREIGN KEY (ID_BAIRRO)
    REFERENCES BAIRRO(ID);
    
ALTER TABLE ENDERECO ADD CONSTRAINT FK_RUA
    FOREIGN KEY (ID_RUA)
    REFERENCES RUA(ID);
    
ALTER TABLE INFORMACOES_PESSOAIS ADD CONSTRAINT FK_ENDERECO
    FOREIGN KEY (ID_ENDERECO)
    REFERENCES ENDERECO(ID);
    
ALTER TABLE CONTATO_EMPRESA ADD CONSTRAINT FK_INFORMACOES_PESSOAIS
    FOREIGN KEY (ID_INFORMACOES_PESSOAIS)
    REFERENCES INFORMACOES_PESSOAIS(ID);
    
ALTER TABLE DADOS_EMPRESARIAIS ADD CONSTRAINT FK_CONTATO_EMPRESA
    FOREIGN KEY (ID_CONTATO_EMPRESA)
    REFERENCES CONTATO_EMPRESA(ID);
    
ALTER TABLE DADOS_EMPRESARIAIS ADD CONSTRAINT FK_PRODUTO
    FOREIGN KEY (ID_PRODUTO)
    REFERENCES PRODUTO(ID);
    
ALTER TABLE DADOS_EMPRESARIAIS ADD CONSTRAINT FK_ENDERECO_DADOS_EMPRESARIAIS
    FOREIGN KEY (ID_ENDERECO)
    REFERENCES ENDERECO(ID);
    
    
DESC ESTADO;

DROP TABLE DADOS_EMPRESARIAIS;