DROP TABLE ch_estoque CASCADE CONSTRAINTS;
DROP TABLE ch_cliente CASCADE CONSTRAINTS;
CREATE TABLE ch_cliente (
    cod_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL,
    sobrenome VARCHAR2(50) NOT NULL,
    data_nascimento DATE NOT NULL,
    telefone VARCHAR2(14) NOT NULL,
    email_corporativo VARCHAR2(100) NOT NULL,
    nome_usuario VARCHAR2(50) NOT NULL,
    senha VARCHAR2(50) NOT NULL
);

CREATE TABLE ch_estoque (
    cod_estoque NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ch_cliente_cod_cliente NUMBER NOT NULL,
    FOREIGN KEY (ch_cliente_cod_cliente) REFERENCES ch_cliente(cod_cliente)
);

INSERT INTO ch_cliente (nome, sobrenome, data_nascimento, telefone, email_corporativo, nome_usuario, senha)
VALUES ('João', 'Silva', TO_DATE('1985-05-15', 'YYYY-MM-DD'), '1198765-4321', 'joao.silva@empresa.com', 'joaosilva', 'senha123');

INSERT INTO ch_cliente (nome, sobrenome, data_nascimento, telefone, email_corporativo, nome_usuario, senha)
VALUES ('Maria', 'Oliveira', TO_DATE('1990-10-20', 'YYYY-MM-DD'), '1191234-5678', 'maria.oliveira@empresa.com', 'mariaoliveira', 'senha456');

INSERT INTO ch_cliente (nome, sobrenome, data_nascimento, telefone, email_corporativo, nome_usuario, senha)
VALUES ('Carlos', 'Pereira', TO_DATE('1982-03-10', 'YYYY-MM-DD'), '1196543-2109', 'carlos.pereira@empresa.com', 'carlospereira', 'senha789');

INSERT INTO ch_cliente (nome, sobrenome, data_nascimento, telefone, email_corporativo, nome_usuario, senha)
VALUES ('Ana', 'Costa', TO_DATE('1975-08-25', 'YYYY-MM-DD'), '1193456-7890', 'ana.costa@empresa.com', 'anacosta', 'senha101');

INSERT INTO ch_cliente (nome, sobrenome, data_nascimento, telefone, email_corporativo, nome_usuario, senha)
VALUES ('Bruno', 'Martins', TO_DATE('1988-12-30', 'YYYY-MM-DD'), '1198765-1234', 'bruno.martins@empresa.com', 'brunomartins', 'senha102');

INSERT INTO ch_cliente (nome, sobrenome, data_nascimento, telefone, email_corporativo, nome_usuario, senha)
VALUES ('Fernanda', 'Souza', TO_DATE('1995-07-14', 'YYYY-MM-DD'), '1194321-8765', 'fernanda.souza@empresa.com', 'fernandasouza', 'senha103');

INSERT INTO ch_cliente (nome, sobrenome, data_nascimento, telefone, email_corporativo, nome_usuario, senha)
VALUES ('Ricardo', 'Almeida', TO_DATE('1983-11-22', 'YYYY-MM-DD'), '1195678-1234', 'ricardo.almeida@empresa.com', 'ricardoalmeida', 'senha104');

INSERT INTO ch_cliente (nome, sobrenome, data_nascimento, telefone, email_corporativo, nome_usuario, senha)
VALUES ('Patricia', 'Lima', TO_DATE('1992-06-05', 'YYYY-MM-DD'), '1193456-4321', 'patricia.lima@empresa.com', 'patricialima', 'senha105');

INSERT INTO ch_cliente (nome, sobrenome, data_nascimento, telefone, email_corporativo, nome_usuario, senha)
VALUES ('Thiago', 'Fernandes', TO_DATE('1989-09-17', 'YYYY-MM-DD'), '1199876-5432', 'thiago.fernandes@empresa.com', 'thiagofernandes', 'senha106');

INSERT INTO ch_cliente (nome, sobrenome, data_nascimento, telefone, email_corporativo, nome_usuario, senha)
VALUES ('Juliana', 'Gomes', TO_DATE('1987-04-19', 'YYYY-MM-DD'), '1196543-0987', 'juliana.gomes@empresa.com', 'julianagomes', 'senha107');

commit;

